### 배열 생성하기
- Numpy는 Numeric Python의 줄임말
- 수학분야 관련된 통계 연상 작업시 필요한 라이브러리
- 과학 계산 컴퓨팅과 데이터 분석에 필요한 가장 기본적인 패키지

Numpy 배열은 리스트와 거의 흡사하지만
연산속도가 빠르고 메모리 효율성이 높아서 대용량 데이터를 다루는데 성능상 우위를 차지한다.

사용하기 전에 아래와 같이 라이브러리 모듈을 import 해야한다.

Numpy 배열을 만든 방법
1) array() 사용 
2) random 랜덤함수 사용

In [1]:
import numpy as np

### np배열 생성

In [16]:
'''
리스트와 numpy배열을 각각 생성하고 두개를 비교해보자


1) array() 사용

::
1.
리스트는 출력 결과가 [ ]안에 들어오고 각 요소들이 ,(콤마)로 구분된다
np 배열은 출력 결과가 [ ]안에 들어오고 각 요소들이 콤마로 구분없이 그냥 나열된다.
::
2.
np 배열의 타입은 ndarray 타입
::
ndarray 클래스
다차원 행렬구조를 지원하는 Numpy의 핵심 클래스
'''
myList = [4, 5, 6, 7]   #기본 list
myList

myArr = np.array(myList)

print(myList)
print(myArr)
print("list type: ", type(myList)) 
print("numpy arry type: ", type(myArr))

[4, 5, 6, 7]
[4 5 6 7]
list type:  <class 'list'>
numpy arry type:  <class 'numpy.ndarray'>


### 슬라이싱과 인덱싱

In [15]:
list_sub = myList[1:3]  # 슬라이싱(숫자일때는 뒷부분 숫자가 포함되지 않는다)
print(list_sub)

arr_sub = myArr[1:3]
print(arr_sub)

list_sub[0] = -5
arr_sub[0] = -5

print(list_sub)
print(arr_sub)

[5, 6]
[5 6]
[-5, 6]
[-5  6]


### 리스트와 np배열의 차이점
리스트는 원본이 안바뀐다. 원본을 카피해서 새로운걸 만든다. <br>
np배열은 원본이 바뀐다.<br>
::
메모리 활용적인 성능면에서는 np배열이 성능이 좋아진다.<br>

In [13]:
print(myList)
print(myArr)  # [ 4 -5  6  7] 위에서 슬라이싱을 해서 변경 했던 것을 원본 numpy Array도 바뀐다.

[4, 5, 6, 7]
[ 4 -5  6  7]


### Numpy 배열 생성 
- random 함수 사용

In [17]:
a = np.random.rand?   # ?는 도움말 보기

In [43]:
a = np.random.rand(5)  # 5개의 랜덤 숫자 출력
print(a)
print(type(a))

''' randint(최소값, 최대값, 개수)'''
b = np.random.randint(1, 10, 5)  # 1부터 10까지의 숫자 중에 5개를 추출
print(b)

c = np.random.randn(10) # 가우시안 표준분포 값
print(c)  # 10개의 랜덤 숫자 출력

[0.40981397 0.64958551 0.66823093 0.02399315 0.19954616]
<class 'numpy.ndarray'>
[1 9 6 7 7]
[-0.02953595  0.33875445  0.11334091  0.20135796  0.40057503 -0.49801236
 -0.68696575 -0.7512197   0.62532852 -1.71910134]


### Numpy 배열 생성과 동시에 초기화 

* zeros(), ones(), arange() 사용

In [44]:
# 0으로 초기화
# 값이 0.0(실수형)으로 이루어진 크기가 10인 배열을 생성
az = np.zeros(10)
print(az)  # float 타입으로 만들어짐  0.0

# 1(float) 값으로 이뤄진 크기가 10인 배열 생성
ao = np.ones(10)
print(ao)

# 5라는 값으로 이뤄진 크기가 10인 배열 생성
af = np.zeros(10) + 5   # 초기화 값인 0에 5를 더해서 10개 생성
print(af)
af_2 = np.ones(10) + 4   # 초기화 값인 1에 4를 더해서 10개 생성
print(af_2)
af_3 = np.ones(10) * 5
print(af_3)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [45]:
'''
2차원 [[]]   Matrix
1차원 []     Vector
'''
ae = np.eye(3)
print(ae)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [46]:
# arange() 사용
print(np.arange(0,3))  # 무조건 row size는 0이다
print(np.arange(3))
print(np.arange(3,7))
print(np.arange(3,10,2))  # 2는 step을 의미

[0 1 2]
[0 1 2]
[3 4 5 6]
[3 5 7 9]


In [47]:
# full()
afull = np.full((5,5), -11)  # 5행 5열을 -11로 초기화 
print(afull)

[[-11 -11 -11 -11 -11]
 [-11 -11 -11 -11 -11]
 [-11 -11 -11 -11 -11]
 [-11 -11 -11 -11 -11]
 [-11 -11 -11 -11 -11]]
